### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by Sergey2311** [Sergey2311/post#1]
// video
/*
const videoEl = document.createElement('video');
videoEl.controls = true; // здесь не пустой, а именно true
rootEl.appendChild(videoEl);
*/  (это Ваш пример из лекции)

Не понял смысл добавлять информацию по видео и аудио в файл app.js, поскольку все работает и с прописью только в index.html. Пробовал прописать по аналогии второй и третий пост в app.js соответственно с аудио и видео, но связи не заметил. 
Прошу пояснить как настроить взаимосвязь если ДЗ сделано неверно.

**Comment by coursar** [comment]
Нужно научиться программно генерировать все виды постов без необходимости это явно прописывать в HTML.

Если вы зайдёте во Вк, там не прописано всё в HTML, а создаётся динамически, через JavaScript.

**Comment by Sergey2311** [comment]
Прошу проверить commit "Третий вариант". 
Только не могу понять почему в первом посте кнопки "лайк" и "дизлайк" получились другого размера. Прописано вроде все по аналогии.

**Comment by Sergey2311** [comment]
https://sergey2311.github.io/post/

**Comment by coursar** [comment]
Потому что в двух нижних карточках вы забыли `class="card-body"`
